python -O ./run.py new --seed=22 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_22 --record-outfile=45.json
python -O ./run.py new --seed=19 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_19 --record-outfile=39.json
python -O ./run.py policy_iteration --seed=11 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_11 --record-outfile=22.json
python -O ./run.py policy_iteration --seed=9 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_9 --record-outfile=18.json
python -O ./run.py policy_iteration --seed=25 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_25 --record-outfile=50.json
python -O ./run.py policy_iteration --seed=8 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_8 --record-outfile=16.json
python -O ./run.py policy_iteration --seed=24 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_24 --record-outfile=48.json
python -O ./run.py new --seed=28 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_28 --record-outfile=57.json
python -O ./run.py policy_iteration --seed=15 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_15 --record-outfile=30.json
python -O ./run.py new --seed=17 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_17 --record-outfile=35.json
python -O ./run.py new --seed=29 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_29 --record-outfile=59.json
python -O ./run.py policy_iteration --seed=10 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_10 --record-outfile=20.json
python -O ./run.py policy_iteration --seed=12 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_12 --record-outfile=24.json
python -O ./run.py new --seed=27 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_27 --record-outfile=55.json
python -O ./run.py new --seed=7 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_7 --record-outfile=15.json
python -O ./run.py new --seed=2 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_2 --record-outfile=5.json
python -O ./run.py policy_iteration --seed=18 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_18 --record-outfile=36.json
python -O ./run.py policy_iteration --seed=3 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_3 --record-outfile=6.json
python -O ./run.py new --seed=26 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_26 --record-outfile=53.json
python -O ./run.py policy_iteration --seed=22 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_22 --record-outfile=44.json
python -O ./run.py new --seed=13 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_13 --record-outfile=27.json
python -O ./run.py policy_iteration --seed=1 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_1 --record-outfile=2.json
python -O ./run.py policy_iteration --seed=2 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_2 --record-outfile=4.json
python -O ./run.py policy_iteration --seed=19 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_19 --record-outfile=38.json
python -O ./run.py new --seed=1 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_1 --record-outfile=3.json
python -O ./run.py new --seed=12 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_12 --record-outfile=25.json
python -O ./run.py policy_iteration --seed=6 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_6 --record-outfile=12.json
python -O ./run.py new --seed=3 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_3 --record-outfile=7.json
python -O ./run.py new --seed=21 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_21 --record-outfile=43.json
python -O ./run.py new --seed=18 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_18 --record-outfile=37.json
python -O ./run.py policy_iteration --seed=14 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_14 --record-outfile=28.json
python -O ./run.py policy_iteration --seed=16 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_16 --record-outfile=32.json
python -O ./run.py policy_iteration --seed=23 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_23 --record-outfile=46.json
python -O ./run.py policy_iteration --seed=21 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_21 --record-outfile=42.json
python -O ./run.py new --seed=25 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_25 --record-outfile=51.json
python -O ./run.py new --seed=20 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_20 --record-outfile=41.json
python -O ./run.py new --seed=14 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_14 --record-outfile=29.json
python -O ./run.py new --seed=4 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_4 --record-outfile=9.json
python -O ./run.py policy_iteration --seed=13 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_13 --record-outfile=26.json
python -O ./run.py policy_iteration --seed=7 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_7 --record-outfile=14.json
python -O ./run.py new --seed=15 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_15 --record-outfile=31.json
python -O ./run.py policy_iteration --seed=26 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_26 --record-outfile=52.json
python -O ./run.py new --seed=23 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_23 --record-outfile=47.json
python -O ./run.py new --seed=0 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_0 --record-outfile=1.json
python -O ./run.py policy_iteration --seed=4 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_4 --record-outfile=8.json
python -O ./run.py new --seed=6 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_6 --record-outfile=13.json
python -O ./run.py new --seed=10 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_10 --record-outfile=21.json
python -O ./run.py new --seed=11 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_11 --record-outfile=23.json
python -O ./run.py policy_iteration --seed=27 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_27 --record-outfile=54.json
python -O ./run.py policy_iteration --seed=28 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_28 --record-outfile=56.json
python -O ./run.py new --seed=16 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_16 --record-outfile=33.json
python -O ./run.py policy_iteration --seed=17 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_17 --record-outfile=34.json
python -O ./run.py policy_iteration --seed=29 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_29 --record-outfile=58.json
python -O ./run.py new --seed=8 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_8 --record-outfile=17.json
python -O ./run.py new --seed=9 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_9 --record-outfile=19.json
python -O ./run.py new --seed=5 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_5 --record-outfile=11.json
python -O ./run.py policy_iteration --seed=5 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_5 --record-outfile=10.json
python -O ./run.py policy_iteration --seed=20 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_20 --record-outfile=40.json
python -O ./run.py policy_iteration --seed=0 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=policy_iteration_0 --record-outfile=0.json
python -O ./run.py new --seed=24 --gamma=0.9 --epsilon=1e-9 --num-iter=25 --use-wandb=new_24 --record-outfile=49.json
